export const contactFooterStyles = {
  container: "bg-gradient-to-r from-blue-600 to-blue-800 py-16",
  contentWrapper: "container mx-auto",
  gridContainer: "grid grid-cols-1 lg:grid-cols-2 gap-12 items-center",
  textContainer: "text-white",
  title: "text-4xl font-bold mb-6",
  description: "mb-6 text-lg",
  slogan: "text-2xl font-bold mb-8",
  contactContainer: "space-y-4 mb-8",
  contactItem: "flex items-center gap-4",
  iconContainer: "w-12 h-12 bg-[#F97316] rounded-full flex items-center justify-center",
  icon: "text-white",
  phoneText: "text-xl",
  addressText: "text-lg",
  socialText: "mb-4 text-xl",
  socialContainer: "flex items-center gap-6",
  socialLink: "transition-transform hover:scale-110",
  logo: "h-12 w-auto",
  socialIcon: "h-10 w-10",
  instagramIcon: "text-pink-500",
  facebookIcon: "text-blue-500",
  youtubeIcon: "text-red-500",
  imageContainer: "w-full",
  image: "w-full h-auto rounded-lg shadow-lg"
}; 